### ISSUE TITLE
Bulbasaur is missing

### ISSUE THREAD

**Issue by Joomsy** [mariinkys/starrydex#8]
Built the app from Git, and Bulbasaur is missing from the roster. Haven't tried the Flatpak build, but I did renew the cache, and that didn't help.

![screenshot-2024-10-12-21-21-56](https://github.com/user-attachments/assets/8a43b1da-f7be-4155-a3b4-4b102b7173ac)

![screenshot-2024-10-12-21-22-15](https://github.com/user-attachments/assets/3a9e0f79-f008-4c83-9de5-e7063845080e)

**Comment by mariinkys** [comment]
Should be fixed right now, it happens on the Flatpak too will publish an update asap.

**Comment by Joomsy** [comment]
> Should be fixed right now, it happens on the Flatpak too will publish an update asap.

Nice! Looks good from my end. Thanks for looking into this. :)
